### PR TITLE
pushing react-week4 h/w

### PR DESCRIPTION
**Pull request by mamathamereddy**

### CODE REVIEW

**Comment by senner007** [comment]
Hi :)
Is the code working on your end?
I only get a reply on every second letter I type.

**Comment by mamathamereddy** [comment]
> Hi :)
> Is the code working on your end?
> I only get a reply on every second letter I type.

**Comment by mamathamereddy** [comment]
> Hi :)
> Is the code working on your end?
> I only get a reply on every second letter I type.

**Comment by mamathamereddy** [comment]
made changes working fine now

**Pull request merged**
